### ISSUE TITLE
Problem with test ct004

### ISSUE THREAD

**Issue by JaviMuller** [diogotcorreia/kanban-iaed-tests#18]
In problem ct004, after registering all tasks, there are multiple calls for m commands. (lines 2912-2921), user "needed' wasn't declared, so all of them should print a "no such user message" however, if you check the dump of stdout in ct004.out, the lines corresponding to the commands from line 2916-2921 are the next:
```
        m 1483 needed TO DO
        n 94
        m 2624 needed DONE
        m 697 needed TO DO
        m 2524 needed IN PROGRESS
        m 2407 needed DONE
```
while the corresponding output (lines 14535-14538) is:
```
194
no such user
no such user
no such user
```
the same happens with input 2939, 3061 and 3229, having no output (that should be at lines 107997, 110935 and 257735, respectively). I have one more error of the same type which I believe being due to the same cause but do not know the input to relate it to at the lines of output 107997.

**Comment by diogotcorreia** [comment]
This is expected behavior.

![image](https://user-images.githubusercontent.com/7467891/113998858-5f164500-9851-11eb-809b-a2a010094ab5.png)

All the error messages, except `no such task`, are only thrown if the task is actually moved (i.e. the task is **not** in the activity you're trying to move it to).
